# Generated by Django 4.1.1 on 2022-09-15 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(related_name='posts', to='app.category'),
        ),
        migrations.AlterField(
            model_name='user',
            name='major1',
            field=models.ManyToManyField(related_name='users', to='app.major1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='major2',
            field=models.ManyToManyField(related_name='users', to='app.major2'),
        ),
    ]
