# Generated by Django 4.1.1 on 2022-09-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_post_category_alter_user_major1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majoradvance',
            name='majoradvance',
            field=models.CharField(max_length=16),
        ),
    ]
