# Generated by Django 4.1.1 on 2022-09-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_majoradvance_majoradvance'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(default=None, max_length=16),
        ),
    ]
